### ISSUE TITLE
ifdnfc-activate issue for SPI port

### ISSUE THREAD

**Issue by ronie19** [neomilium/ifdnfc#8]
root@raspberrypi:~$sudo ifdnfc-activate

2 NFC devices found, please select one:
[0] pn532_spi:/dev/spidev0.0 (pn532_spi:/dev/spidev0.0:50000)
[1] pn532_spi:/dev/spidev0.0 (pn532_spi:/dev/spidev0.0:1000000)

0
Activating ifdnfc with "pn532_spi:/dev/spidev0.0:50000"...
Insufficient buffer.

How to deal with this buffer issue ?

**Comment by neomilium** [comment]
Please:
1) Use a clean markdown format (read the markdown doc about code blocks)
2) Dig a bit before asking questions: your problem is related to `libnfc`, not `ifdnfc`
3) Read the `libnfc` documentation files: `README.md`, `HACKING.md`, etc. to found how to debug your problem
